# Generated by Django 4.1 on 2022-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_katalog_poryadok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='setting/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='setting',
            name='banner',
        ),
        migrations.AlterField(
            model_name='katalog',
            name='image',
            field=models.ImageField(upload_to='setting/images/'),
        ),
        migrations.AlterField(
            model_name='poryadok',
            name='image',
            field=models.ImageField(upload_to='setting/images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(upload_to='setting/images/'),
        ),
    ]
