# Generated by Django 4.1 on 2022-08-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_banner_remove_setting_banner_alter_katalog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='opisanie',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
