# Generated by Django 4.1 on 2022-08-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_setting_opisanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='zagolovok',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
