# Generated by Django 4.1 on 2022-08-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_banner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='pod_description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
