# Generated by Django 4.1 on 2022-08-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_banner_pod_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
