# Generated by Django 4.1 on 2022-08-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_alter_setting_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.ImageField(upload_to='setting/images/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='pod_description',
            field=models.CharField(max_length=250, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='image',
            field=models.ImageField(upload_to='setting/images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название категории в каталоге'),
        ),
        migrations.AlterField(
            model_name='poryadok',
            name='image',
            field=models.ImageField(upload_to='setting/images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='poryadok',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(upload_to='setting/images/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='mail',
            field=models.CharField(max_length=200, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='opisanie',
            field=models.CharField(max_length=250, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='zagolovok',
            field=models.CharField(max_length=250, verbose_name='Дополнительный слоган'),
        ),
    ]
