# Generated by Django 4.1 on 2022-08-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_alter_banner_banner_alter_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннер'},
        ),
        migrations.AlterModelOptions(
            name='katalog',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталог'},
        ),
        migrations.AlterModelOptions(
            name='poryadok',
            options={'verbose_name': 'Преимущества', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Общие настройки', 'verbose_name_plural': 'Общие настройки'},
        ),
    ]
