# Generated by Django 4.1 on 2022-08-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_alter_banner_options_alter_katalog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('opisanie_1', models.CharField(max_length=250, verbose_name='Первое описание')),
                ('opisanie_2', models.CharField(max_length=250, verbose_name='Второе описание')),
                ('banner_2', models.ImageField(upload_to='setting/images/', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Баннер - полный каталог',
                'verbose_name_plural': 'Баннер - полный каталог',
            },
        ),
    ]
