# Generated by Django 4.1 on 2022-09-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_banner_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreimVa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='setting/images/', verbose_name='Иконка')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Этапы работы',
                'verbose_name_plural': 'Этапы работы',
            },
        ),
    ]
