# Generated by Django 4.1 on 2022-09-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_preimva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='setting/images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Примеры работ',
                'verbose_name_plural': 'Примеры работ',
            },
        ),
    ]
